---
- name: "Register worker token"
  delegate_to: localhost
  become: false
  shell: cat /tmp/manager.token
  register: manager_token

- name: "Register {{inventory_hostname}} to swarm"
  shell: "docker swarm join --token {{manager_token.stdout}} 192.168.8.2"
  when: hostname != "vm-node1"
...
