---
- name: init swarm
  hosts: vms
  order: sorted
  any_errors_fatal: true
  become_user: root
  become: yes
  user: root
  gather_facts: false
  vars_files:
  - vars/conn
  - vars/virt

  tasks:
  

  - name: "Register worker token"
    delegate_to: localhost
    become: false
    shell: cat /tmp/manager.token
    register: manager_token

  - name: "Register {{inventory_hostname}} to swarm"
    shell: "docker swarm join --token {{manager_token.stdout}} 192.168.8.2"
    when: hostname != "vm-node1"
...
