---
- name: Install last Docker version
  shell: curl -sSL https://get.docker.com/ | sh
  args:
    warn: no

- name: Install last docker-compose
  shell: |
    curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" \
        -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose 

    chmod +x /usr/local/bin/docker-compose
    ln -sf /usr/local/bin/docker-compose /usr/bin/docker-compose
  args:
    executable: /usr/bin/sh
    warn: no

- name: enable and start docker daemon
  systemd:
    name: docker
    state: started
    enabled: yes

...