---
- name: Install last Docker version
  shell: curl -sSL https://get.docker.com/ | sh
  args:
    warn: no

- name: Install last docker-compose
  shell: |
    curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" \
        -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose 

    chmod +x /usr/local/bin/docker-compose
    ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
  args:
    executable: /usr/bin/sh
    warn: no

- name: enable and start docker daemon
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Enable socket tcp
  shell: |
    cp /lib/systemd/system/docker.service /root/docker.service.backup \
    sed -i 's/--containerd=\/run\/containerd\/containerd.sock/-H tcp:\/\/0.0.0.0:2375/g' /lib/systemd/system/docker.service \
    systemctl daemon-reload
    systemctl restart docker
  args:
    executable: /usr/bin/sh
    warn: no
...