---
- name: Main Task to Create Virtual Machines
  hosts: vms
  order: sorted
  any_errors_fatal: true
  become_user: root
  become: yes
  user: root
  gather_facts: false
  vars_files:
  - vars/conn
  - vars/virt
  tasks:

  - name: Create network
    import_role:
        name: libvirt
        tasks_from: prepare.yml
    delegate_to: localhost
    connection: local
    when: stat_result is not defined

  - name: Create virtual machine
    import_role:
        name: libvirt
        tasks_from: create.yml
    connection: local
    delegate_to: localhost

  - name: Fix storage
    import_role:
        name: libvirt
        tasks_from: storage.yml
    connection: local
    delegate_to: localhost

  - name: Configure virtual machine
    import_role:
      name: os
      tasks_from: setup.yml

  - name: Include Container Engine
    import_role:
        name: docker
        tasks_from: main.yml

  - name: Make docker secure with SSL on REST API
    include_role:
      name: docker
      tasks_from: protect.yml

  - name: Copy client cert on local
    include_role:
      name: docker
      tasks_from: getcert.yml
      
  - name: Start docker swarm
    include_role:
      name: docker
      tasks_from: init_swarm.yml

  - name: Add manager/worker to swarm
    include_role:
      name: docker
      tasks_from: add_node.yml
...
