---
- name: Main Task to check status of vms
  hosts: all
  any_errors_fatal: true
  become_user: root
  become: yes
  user: root
  gather_facts: false
  vars_files:
  - vars/conn
  - vars/virt
  tasks:
  - ping:


