---
- name: Main Task to edit storage disk of Virtual Machines
  hosts: vms
  order: sorted
  any_errors_fatal: true
  become_user: root
  become: yes
  user: root
  gather_facts: false
  vars_files:
  - vars/conn
  - vars/virt
  tasks:
  - name: Configure virtual machine
    import_role:
      name: libvirt
      tasks_from: storage.yml

...
